name: docker build & push

on: workflow_dispatch

jobs:
  build and push:
   runs-on: ubuntu-latest
   steps:
     - name: code checkout
       uses: actions/checkout@v4

     - name: login to docker hub
       uses: docker/login-action@v3
       with:
         Username: ${{vars.DOCKERHUB_USER}}
         password: ${{vars.DOCKERHUB_TOKEN}}
     - name: build and push to docker hub
       uses: docker/build-push-action@v6
       with:
         push: true
         tag: ${{vars.DOCKERHUB_USER}}/app:latest
